# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
<<<<<<< HEAD
    branches: [ "one" ]
  pull_request:
    branches: [ "main" ]
=======
    branches:
    - main
  #pull_request:
   # branches: [ "main" ]
>>>>>>> origin/one

 # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checking:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
<<<<<<< HEAD
      - name : updating repo
        run : git pull origin main
     # - name: check node version
      #  run: node -v
      #- name : use nvm
       # run : nvm use 12.13.1
      #- name : nvm list
       # run : nvm list
=======
      - name: check node version
        run: git pull origin one
      #- name : use nvm
       # run : nvm use 12.13.1
      #- name : nvm list
      #  run : nvm list
>>>>>>> origin/one
      #- name : node version
      #  run : node -v
      
